--liquibase formatted sql

--changeset author:alvi
INSERT INTO bankname (bank_name) VALUES ('RUPALI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('STANDARD BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('JANATA BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('AL-ARAFAH ISLAMI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('COMMUNITY BANK BANGLADESH LTD.');
INSERT INTO bankname (bank_name) VALUES ('MODHUMOTI BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('EASTERN BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('AB BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('GLOBAL ISLAMI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BANK ASIA LTD.');
INSERT INTO bankname (bank_name) VALUES ('MIDLAND BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('BANGLADESH BANK');
INSERT INTO bankname (bank_name) VALUES ('BANGLADESH DEVELOPMENT BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BANGLADESH COMMERCE BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('NATIONAL BANK OF PAKISTAN');
INSERT INTO bankname (bank_name) VALUES ('BANGLADESH KRISHI BANK');
INSERT INTO bankname (bank_name) VALUES ('IFIC BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('MERCANTILE BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('UNITED COMMERCIAL BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('PUBALI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BANK AL-FALAH LTD');
INSERT INTO bankname (bank_name) VALUES ('SHAHJALAL ISLAMI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('RAJSHAHI KRISHI UNNAYAN BANK');
INSERT INTO bankname (bank_name) VALUES ('CITI BANK N A');
INSERT INTO bankname (bank_name) VALUES ('MUTUAL TRUST BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BRAC BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('NATIONAL CREDIT & COMMERCE BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('THE CITY BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('CITIZENS BANK PLC');
INSERT INTO bankname (bank_name) VALUES ('BANGLADESH SAMABAYA BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('AGRANI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('JAMUNA BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('ISLAMI BANK BANGLDESH LTD.');
INSERT INTO bankname (bank_name) VALUES ('NRB COMMERCIAL BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('WOORI BANK');
INSERT INTO bankname (bank_name) VALUES ('HABIB BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('ICB ISLAMIC BANK LTD');
INSERT INTO bankname (bank_name) VALUES ('TRUST BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('SOUTHEAST BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('SOCIAL ISLAMI BANK LTD');
INSERT INTO bankname (bank_name) VALUES ('ONE BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('MEGHNA BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('COMMERCIAL BANK OF CYLON');
INSERT INTO bankname (bank_name) VALUES ('EXIM BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('SONALI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('SBAC BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('DUTCH-BANGLA BANK LTD');
INSERT INTO bankname (bank_name) VALUES ('STATE BANK OF INDIA');
INSERT INTO bankname (bank_name) VALUES ('STANDARD CHARTERED BANK');
INSERT INTO bankname (bank_name) VALUES ('UNION BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('NRB BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('HONGKONG & SHANGHAI BANKING CORP.');
INSERT INTO bankname (bank_name) VALUES ('THE PREMIER BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('UTTARA BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BENGAL COMMERCIAL BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('PRIME BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('BASIC BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('NATIONAL BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('DHAKA BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('FIRST SECURITY ISLAMI BANK LTD.');
INSERT INTO bankname (bank_name) VALUES ('PADMA BANK LIMITED');
INSERT INTO bankname (bank_name) VALUES ('SHIMANTO BANK LIMITED');
