--liquibase formatted sql

--changeset author:alvi
INSERT INTO citycorporation (name) VALUES ('DHAKA NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('DHAKA SOUTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('CHATTOGRAM NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('SYLHET NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('BARISAL NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('KHULNA NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('RAJSHAHI NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('GAZIPUR NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('NARAYANGANJ NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('RANGPUR NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('CUMILLA NORTH CITY CORPORATION');
INSERT INTO citycorporation (name) VALUES ('MYMENSINGH NORTH CITY CORPORATION');
