--liquibase formatted sql

--changeset author:alvi
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (1, 1, 'BARISAL', '4', 'BARGUNA', '9', 'AMTALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (2, 1, 'BARISAL', '4', 'BARGUNA', '19', 'BAMNA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (3, 1, 'BARISAL', '4', 'BARGUNA', '28', 'BARGUNA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (4, 1, 'BARISAL', '4', 'BARGUNA', '47', 'BETAGI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (5, 1, 'BARISAL', '4', 'BARGUNA', '85', 'PATHARGHATA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (6, 1, 'BARISAL', '4', 'BARGUNA', '92', 'TALTOLI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (7, 1, 'BARISAL', '6', 'BARISAL', '2', 'AGAILJHARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (8, 1, 'BARISAL', '6', 'BARISAL', '3', 'BABUGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (9, 1, 'BARISAL', '6', 'BARISAL', '7', 'BAKERGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (10, 1, 'BARISAL', '6', 'BARISAL', '10', 'BANARI PARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (11, 1, 'BARISAL', '6', 'BARISAL', '32', 'GAURNADI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (12, 1, 'BARISAL', '6', 'BARISAL', '36', 'HIZLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (13, 1, 'BARISAL', '6', 'BARISAL', '51', 'BARISAL SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (14, 1, 'BARISAL', '6', 'BARISAL', '62', 'MHENDIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (15, 1, 'BARISAL', '6', 'BARISAL', '69', 'MULADI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (16, 1, 'BARISAL', '6', 'BARISAL', '94', 'WAZIRPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (17, 1, 'BARISAL', '9', 'BHOLA', '18', 'BHOLA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (18, 1, 'BARISAL', '9', 'BHOLA', '21', 'BURHANUDDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (19, 1, 'BARISAL', '9', 'BHOLA', '25', 'CHAR FASSO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (20, 1, 'BARISAL', '9', 'BHOLA', '29', 'DAULAT KHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (21, 1, 'BARISAL', '9', 'BHOLA', '54', 'LALMOHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (22, 1, 'BARISAL', '9', 'BHOLA', '65', 'MANPURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (23, 1, 'BARISAL', '9', 'BHOLA', '91', 'TAZUMUDDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (24, 1, 'BARISAL', '42', 'JHALOKATI', '40', 'JHALOKATI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (25, 1, 'BARISAL', '42', 'JHALOKATI', '43', 'KANTHALIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (26, 1, 'BARISAL', '42', 'JHALOKATI', '73', 'NALCHITY')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (27, 1, 'BARISAL', '42', 'JHALOKATI', '84', 'RAJAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (28, 1, 'BARISAL', '78', 'PATUAKHALI', '38', 'BAUPHAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (29, 1, 'BARISAL', '78', 'PATUAKHALI', '52', 'DASHMINA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (30, 1, 'BARISAL', '78', 'PATUAKHALI', '55', 'DUMKI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (31, 1, 'BARISAL', '78', 'PATUAKHALI', '57', 'GALACHIPA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (32, 1, 'BARISAL', '78', 'PATUAKHALI', '66', 'KALA PARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (33, 1, 'BARISAL', '78', 'PATUAKHALI', '76', 'MIRZAGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (34, 1, 'BARISAL', '78', 'PATUAKHALI', '95', 'PATUAKHALI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (35, 1, 'BARISAL', '78', 'PATUAKHALI', '97', 'RANGABALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (36, 1, 'BARISAL', '79', 'PIROJPUR', '14', 'BHANDARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (37, 1, 'BARISAL', '79', 'PIROJPUR', '47', 'KAWKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (38, 1, 'BARISAL', '79', 'PIROJPUR', '58', 'MATHBARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (39, 1, 'BARISAL', '79', 'PIROJPUR', '76', 'NAZIRPUR UPAZILA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (40, 1, 'BARISAL', '79', 'PIROJPUR', '80', 'PIROJPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (41, 1, 'BARISAL', '79', 'PIROJPUR', '87', 'NESARABAD (SWARUPKATI)')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (42, 1, 'BARISAL', '79', 'PIROJPUR', '90', 'Indurkani')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (43, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '7', 'BAGHAICHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (44, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '21', 'BARKAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (45, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '25', 'KAWKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (46, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '29', 'BELAI CHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (47, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '36', 'KAPTAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (48, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '47', 'JURAI CHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (49, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '58', 'LANGADU')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (50, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '75', 'NANIARCHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (51, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '78', 'RAJASTHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (52, 2, 'CHATTAGRAM', '84', 'RANGAMATI', '87', 'RANGAMATI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (53, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '7', 'BEGUMGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (54, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '10', 'CHATKHIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (55, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '21', 'COMPANIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (56, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '36', 'HATIYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (57, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '47', 'KABIRHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (58, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '80', 'SENBAGH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (59, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '83', 'SONAIMURI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (60, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '85', 'SUBARNACHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (61, 2, 'CHATTAGRAM', '75', 'NOAKHALI', '87', 'NOAKHALI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (62, 2, 'CHATTAGRAM', '30', 'FENI', '14', 'CHHAGALNAIYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (63, 2, 'CHATTAGRAM', '30', 'FENI', '25', 'DAGANBHUIYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (64, 2, 'CHATTAGRAM', '30', 'FENI', '29', 'FENI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (65, 2, 'CHATTAGRAM', '30', 'FENI', '41', 'FULGAZI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (66, 2, 'CHATTAGRAM', '30', 'FENI', '51', 'PARSHURAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (67, 2, 'CHATTAGRAM', '30', 'FENI', '94', 'SONAGAZI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (68, 2, 'CHATTAGRAM', '3', 'BANDARBA', '4', 'ALIKADAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (69, 2, 'CHATTAGRAM', '3', 'BANDARBA', '14', 'BANDARBAN SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (70, 2, 'CHATTAGRAM', '3', 'BANDARBA', '51', 'LAMA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (71, 2, 'CHATTAGRAM', '3', 'BANDARBA', '73', 'NAIKHONGCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (72, 2, 'CHATTAGRAM', '3', 'BANDARBA', '89', 'ROWANGCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (73, 2, 'CHATTAGRAM', '3', 'BANDARBA', '91', 'RUMA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (74, 2, 'CHATTAGRAM', '3', 'BANDARBA', '95', 'THANCHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (75, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '43', 'DIGHINALA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (76, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '47', 'GUIMARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (77, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '49', 'KHAGRACHHARI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (78, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '61', 'LAKSHMICHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (79, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '65', 'MAHALCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (80, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '67', 'MANIKCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (81, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '70', 'MATIRANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (82, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '77', 'PANCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (83, 2, 'CHATTAGRAM', '46', 'KHAGRACHHARI', '80', 'RAMGARH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (84, 2, 'CHATTAGRAM', '51', 'LAKSHMIPUR', '33', 'KAMALNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (85, 2, 'CHATTAGRAM', '51', 'LAKSHMIPUR', '43', 'LAKSHMIPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (86, 2, 'CHATTAGRAM', '51', 'LAKSHMIPUR', '58', 'ROYPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (87, 2, 'CHATTAGRAM', '51', 'LAKSHMIPUR', '65', 'RAMGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (88, 2, 'CHATTAGRAM', '51', 'LAKSHMIPUR', '73', 'RAMGATI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (89, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '2', 'AKHAURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (90, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '4', 'BANCHHARAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (91, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '7', 'BIJOYNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (92, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '13', 'BRAHMANBARIA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (93, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '33', 'ASHUGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (94, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '63', 'KASBA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (95, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '85', 'NABINAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (96, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '90', 'NASIRNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (97, 2, 'CHATTAGRAM', '12', 'BRAHMANBARIA', '94', 'SARAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (98, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '22', 'CHANDPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (99, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '45', 'FARIDGANJ')
GO
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (100, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '47', 'HAIM CHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (101, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '49', 'HAJIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (102, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '58', 'KACHUA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (103, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '76', 'MATLAB DAKSHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (104, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '79', 'MATLAB UTTAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (105, 2, 'CHATTAGRAM', '13', 'CHANDPUR', '95', 'SHAHRASTI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (106, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '4', 'ANOWARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (107, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '6', 'BAYEJID BOSTAMI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (108, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '8', 'BANSHKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (109, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '10', 'BAKALIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (110, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '12', 'BOALKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (111, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '18', 'CHANDANAISH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (112, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '19', 'CHANDGAO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (113, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '20', 'CHITTAGONG PORT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (114, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '28', 'DOUBLE MOORING')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (115, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '33', 'FATIKCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (116, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '35', 'HALISHAHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (117, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '37', 'HATHAZARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (118, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '39', 'KARNAFULI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (119, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '41', 'KOTWALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (120, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '43', 'KHULSHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (121, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '47', 'LOHAGARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (122, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '53', 'MIRSHARAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (123, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '55', 'PAHARTALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (124, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '57', 'PANCHLAISH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (125, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '61', 'PATIYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (126, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '65', 'PATENGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (127, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '70', 'RANGUNIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (128, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '74', 'RAOZA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (129, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '78', 'SANDWIP')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (130, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '82', 'SATKANIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (131, 2, 'CHATTAGRAM', '15', 'CHITTAGONG', '86', 'SITAKUNDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (132, 2, 'CHATTAGRAM', '19', 'COMILLA', '9', 'BARURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (133, 2, 'CHATTAGRAM', '19', 'COMILLA', '15', 'BRAHMAN PARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (134, 2, 'CHATTAGRAM', '19', 'COMILLA', '18', 'BURICHANG')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (135, 2, 'CHATTAGRAM', '19', 'COMILLA', '27', 'CHANDINA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (136, 2, 'CHATTAGRAM', '19', 'COMILLA', '31', 'CHAUDDAGRAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (137, 2, 'CHATTAGRAM', '19', 'COMILLA', '33', 'COMILLA SADAR DAKSHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (138, 2, 'CHATTAGRAM', '19', 'COMILLA', '36', 'DAUDKANDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (139, 2, 'CHATTAGRAM', '19', 'COMILLA', '40', 'DEBIDWAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (140, 2, 'CHATTAGRAM', '19', 'COMILLA', '54', 'HOMNA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (141, 2, 'CHATTAGRAM', '19', 'COMILLA', '67', 'COMILLA ADARSHA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (142, 2, 'CHATTAGRAM', '19', 'COMILLA', '72', 'LAKSAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (143, 2, 'CHATTAGRAM', '19', 'COMILLA', '73', 'LALMAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (144, 2, 'CHATTAGRAM', '19', 'COMILLA', '74', 'MANOHARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (145, 2, 'CHATTAGRAM', '19', 'COMILLA', '75', 'MEGHNA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (146, 2, 'CHATTAGRAM', '19', 'COMILLA', '81', 'MURADNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (147, 2, 'CHATTAGRAM', '19', 'COMILLA', '87', 'NANGALKOT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (148, 2, 'CHATTAGRAM', '19', 'COMILLA', '94', 'TITAS')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (149, 2, 'CHATTAGRAM', '22', 'Coxbazar', '16', 'CHAKARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (150, 2, 'CHATTAGRAM', '22', 'Coxbazar', '24', 'COX''S BAZAR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (151, 2, 'CHATTAGRAM', '22', 'Coxbazar', '45', 'KUTUBDIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (152, 2, 'CHATTAGRAM', '22', 'Coxbazar', '49', 'MAHESHKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (153, 2, 'CHATTAGRAM', '22', 'Coxbazar', '56', 'PEKUA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (154, 2, 'CHATTAGRAM', '22', 'Coxbazar', '66', 'RAMU')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (155, 2, 'CHATTAGRAM', '22', 'Coxbazar', '90', 'TEKNAF')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (156, 2, 'CHATTAGRAM', '22', 'Coxbazar', '94', 'UKHIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (157, 3, 'DHAKA', '26', 'DHAKA', '2', 'ADABOR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (158, 3, 'DHAKA', '26', 'DHAKA', '4', 'BADDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (159, 3, 'DHAKA', '26', 'DHAKA', '5', 'BANGSHAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (160, 3, 'DHAKA', '26', 'DHAKA', '6', 'BIMAN BANDAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (161, 3, 'DHAKA', '26', 'DHAKA', '8', 'CANTONMENT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (162, 3, 'DHAKA', '26', 'DHAKA', '9', 'CHAK BAZAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (163, 3, 'DHAKA', '26', 'DHAKA', '10', 'DAKSHINKHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (164, 3, 'DHAKA', '26', 'DHAKA', '11', 'DARUS SALAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (165, 3, 'DHAKA', '26', 'DHAKA', '12', 'DEMRA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (166, 3, 'DHAKA', '26', 'DHAKA', '14', 'DHAMRAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (167, 3, 'DHAKA', '26', 'DHAKA', '16', 'DHANMONDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (168, 3, 'DHAKA', '26', 'DHAKA', '18', 'DOHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (169, 3, 'DHAKA', '26', 'DHAKA', '24', 'GANDARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (170, 3, 'DHAKA', '26', 'DHAKA', '26', 'GULSHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (171, 3, 'DHAKA', '26', 'DHAKA', '28', 'HAZARIBAGH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (172, 3, 'DHAKA', '26', 'DHAKA', '29', 'JATRABARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (173, 3, 'DHAKA', '26', 'DHAKA', '30', 'KAFRUL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (174, 3, 'DHAKA', '26', 'DHAKA', '32', 'KADAMTALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (175, 3, 'DHAKA', '26', 'DHAKA', '33', 'KALABAGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (176, 3, 'DHAKA', '26', 'DHAKA', '34', 'KAMRANGIR CHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (177, 3, 'DHAKA', '26', 'DHAKA', '36', 'KHILGAO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (178, 3, 'DHAKA', '26', 'DHAKA', '37', 'KHILKHET')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (179, 3, 'DHAKA', '26', 'DHAKA', '38', 'KERANIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (180, 3, 'DHAKA', '26', 'DHAKA', '40', 'KOTWALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (181, 3, 'DHAKA', '26', 'DHAKA', '42', 'LALBAGH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (182, 3, 'DHAKA', '26', 'DHAKA', '48', 'MIRPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (183, 3, 'DHAKA', '26', 'DHAKA', '50', 'MOHAMMADPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (184, 3, 'DHAKA', '26', 'DHAKA', '54', 'MOTIJHEEL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (185, 3, 'DHAKA', '26', 'DHAKA', '62', 'NAWABGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (186, 3, 'DHAKA', '26', 'DHAKA', '63', 'NEW MARKET')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (187, 3, 'DHAKA', '26', 'DHAKA', '64', 'PALLABI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (188, 3, 'DHAKA', '26', 'DHAKA', '65', 'PALTA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (189, 3, 'DHAKA', '26', 'DHAKA', '66', 'RAMNA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (190, 3, 'DHAKA', '26', 'DHAKA', '67', 'RAMPURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (191, 3, 'DHAKA', '26', 'DHAKA', '68', 'SABUJBAGH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (192, 3, 'DHAKA', '26', 'DHAKA', '72', 'SAVAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (193, 3, 'DHAKA', '26', 'DHAKA', '74', 'SHAH ALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (194, 3, 'DHAKA', '26', 'DHAKA', '75', 'SHAHBAGH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (195, 3, 'DHAKA', '26', 'DHAKA', '76', 'SHYAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (196, 3, 'DHAKA', '26', 'DHAKA', '80', 'SHER-E-BANGLA NAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (197, 3, 'DHAKA', '26', 'DHAKA', '88', 'SUTRAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (198, 3, 'DHAKA', '26', 'DHAKA', '90', 'TEJGAO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (199, 3, 'DHAKA', '26', 'DHAKA', '92', 'TEJGAON IND. AREA')
GO
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (200, 3, 'DHAKA', '26', 'DHAKA', '93', 'TURAG')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (201, 3, 'DHAKA', '26', 'DHAKA', '95', 'UTTARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (202, 3, 'DHAKA', '26', 'DHAKA', '96', 'UTTAR KHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (203, 3, 'DHAKA', '26', 'DHAKA', '98', 'WARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (204, 3, 'DHAKA', '54', 'MADARIPUR', '40', 'KALKINI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (205, 3, 'DHAKA', '54', 'MADARIPUR', '54', 'MADARIPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (206, 3, 'DHAKA', '54', 'MADARIPUR', '80', 'RAJOIR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (207, 3, 'DHAKA', '54', 'MADARIPUR', '87', 'SHIB CHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (208, 3, 'DHAKA', '56', 'MANIKGANJ', '10', 'DAULATPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (209, 3, 'DHAKA', '56', 'MANIKGANJ', '22', 'GHIOR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (210, 3, 'DHAKA', '56', 'MANIKGANJ', '28', 'HARIRAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (211, 3, 'DHAKA', '56', 'MANIKGANJ', '46', 'MANIKGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (212, 3, 'DHAKA', '56', 'MANIKGANJ', '70', 'SATURIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (213, 3, 'DHAKA', '56', 'MANIKGANJ', '78', 'SHIBALAYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (214, 3, 'DHAKA', '56', 'MANIKGANJ', '82', 'SINGAIR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (215, 3, 'DHAKA', '48', 'KISHOREGONJ', '2', 'AUSTAGRAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (216, 3, 'DHAKA', '48', 'KISHOREGONJ', '6', 'BAJITPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (217, 3, 'DHAKA', '48', 'KISHOREGONJ', '11', 'BHAIRAB')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (218, 3, 'DHAKA', '48', 'KISHOREGONJ', '27', 'HOSSAINPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (219, 3, 'DHAKA', '48', 'KISHOREGONJ', '33', 'ITNA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (220, 3, 'DHAKA', '48', 'KISHOREGONJ', '42', 'KARIMGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (221, 3, 'DHAKA', '48', 'KISHOREGONJ', '45', 'KATIADI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (222, 3, 'DHAKA', '48', 'KISHOREGONJ', '49', 'KISHOREGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (223, 3, 'DHAKA', '48', 'KISHOREGONJ', '54', 'KULIAR CHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (224, 3, 'DHAKA', '48', 'KISHOREGONJ', '59', 'MITHAMAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (225, 3, 'DHAKA', '48', 'KISHOREGONJ', '76', 'NIKLI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (226, 3, 'DHAKA', '48', 'KISHOREGONJ', '79', 'PAKUNDIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (227, 3, 'DHAKA', '48', 'KISHOREGONJ', '92', 'TARAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (228, 3, 'DHAKA', '29', 'FARIDPUR', '3', 'ALFADANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (229, 3, 'DHAKA', '29', 'FARIDPUR', '10', 'BHANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (230, 3, 'DHAKA', '29', 'FARIDPUR', '18', 'BOALMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (231, 3, 'DHAKA', '29', 'FARIDPUR', '21', 'CHAR BHADRASA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (232, 3, 'DHAKA', '29', 'FARIDPUR', '47', 'FARIDPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (233, 3, 'DHAKA', '29', 'FARIDPUR', '56', 'MADHUKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (234, 3, 'DHAKA', '29', 'FARIDPUR', '62', 'NAGARKANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (235, 3, 'DHAKA', '29', 'FARIDPUR', '84', 'SADARPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (236, 3, 'DHAKA', '29', 'FARIDPUR', '90', 'SALTHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (237, 3, 'DHAKA', '33', 'GAZIPUR', '30', 'GAZIPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (238, 3, 'DHAKA', '33', 'GAZIPUR', '32', 'KALIAKAIR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (239, 3, 'DHAKA', '33', 'GAZIPUR', '34', 'KALIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (240, 3, 'DHAKA', '33', 'GAZIPUR', '36', 'KAPASIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (241, 3, 'DHAKA', '33', 'GAZIPUR', '86', 'SREEPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (242, 3, 'DHAKA', '35', 'GOPALGANJ', '32', 'GOPALGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (243, 3, 'DHAKA', '35', 'GOPALGANJ', '43', 'KASHIANI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (244, 3, 'DHAKA', '35', 'GOPALGANJ', '51', 'KOTALIPARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (245, 3, 'DHAKA', '35', 'GOPALGANJ', '58', 'MUKSUDPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (246, 3, 'DHAKA', '35', 'GOPALGANJ', '91', 'TUNGIPARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (247, 3, 'DHAKA', '59', 'MUNSHIGANJ', '24', 'GAZARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (248, 3, 'DHAKA', '59', 'MUNSHIGANJ', '44', 'LOHAJANG')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (249, 3, 'DHAKA', '59', 'MUNSHIGANJ', '56', 'MUNSHIGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (250, 3, 'DHAKA', '59', 'MUNSHIGANJ', '74', 'SERAJDIKHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (251, 3, 'DHAKA', '59', 'MUNSHIGANJ', '84', 'SREENAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (252, 3, 'DHAKA', '59', 'MUNSHIGANJ', '94', 'TONGIBARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (253, 3, 'DHAKA', '67', 'NARAYANGANJ', '2', 'ARAIHAZAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (254, 3, 'DHAKA', '67', 'NARAYANGANJ', '4', 'SONARGAO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (255, 3, 'DHAKA', '67', 'NARAYANGANJ', '6', 'BANDAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (256, 3, 'DHAKA', '67', 'NARAYANGANJ', '58', 'NARAYANGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (257, 3, 'DHAKA', '67', 'NARAYANGANJ', '68', 'RUPGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (258, 3, 'DHAKA', '67', 'NARAYANGANJ', '99', 'Siddhirganj')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (259, 3, 'DHAKA', '67', 'NARAYANGANJ', '95', 'Fatullah ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (260, 3, 'DHAKA', '68', 'NARSINGDI', '7', 'BELABO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (261, 3, 'DHAKA', '68', 'NARSINGDI', '52', 'MANOHARDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (262, 3, 'DHAKA', '68', 'NARSINGDI', '60', 'NARSINGDI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (263, 3, 'DHAKA', '68', 'NARSINGDI', '63', 'PALASH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (264, 3, 'DHAKA', '68', 'NARSINGDI', '64', 'ROYPURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (265, 3, 'DHAKA', '68', 'NARSINGDI', '76', 'SHIBPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (266, 3, 'DHAKA', '86', 'SHARIATPUR', '14', 'BHEDARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (267, 3, 'DHAKA', '86', 'SHARIATPUR', '25', 'DAMUDYA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (268, 3, 'DHAKA', '86', 'SHARIATPUR', '36', 'GOSAIRHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (269, 3, 'DHAKA', '86', 'SHARIATPUR', '65', 'NARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (270, 3, 'DHAKA', '86', 'SHARIATPUR', '69', 'SHARIATPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (271, 3, 'DHAKA', '86', 'SHARIATPUR', '94', 'ZANJIRA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (272, 3, 'DHAKA', '93', 'TANGAIL', '9', 'BASAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (273, 3, 'DHAKA', '93', 'TANGAIL', '19', 'BHUAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (274, 3, 'DHAKA', '93', 'TANGAIL', '23', 'DELDUAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (275, 3, 'DHAKA', '93', 'TANGAIL', '25', 'DHANBARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (276, 3, 'DHAKA', '93', 'TANGAIL', '28', 'GHATAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (277, 3, 'DHAKA', '93', 'TANGAIL', '38', 'GOPALPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (278, 3, 'DHAKA', '93', 'TANGAIL', '47', 'KALIHATI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (279, 3, 'DHAKA', '93', 'TANGAIL', '57', 'MADHUPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (280, 3, 'DHAKA', '93', 'TANGAIL', '66', 'MIRZAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (281, 3, 'DHAKA', '93', 'TANGAIL', '76', 'NAGARPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (282, 3, 'DHAKA', '93', 'TANGAIL', '85', 'SAKHIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (283, 3, 'DHAKA', '93', 'TANGAIL', '95', 'TANGAIL SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (284, 3, 'DHAKA', '82', 'RAJBARI', '7', 'BALIAKANDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (285, 3, 'DHAKA', '82', 'RAJBARI', '29', 'GOALANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (286, 3, 'DHAKA', '82', 'RAJBARI', '47', 'KALUKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (287, 3, 'DHAKA', '82', 'RAJBARI', '73', 'PANGSHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (288, 3, 'DHAKA', '82', 'RAJBARI', '76', 'RAJBARI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (289, 3, 'DHAKA', '26', 'DHAKA', '100', 'SHAHJAHANPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (290, 4, 'KHULNA', '65', 'NARAIL', '28', 'KALIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (291, 4, 'KHULNA', '65', 'NARAIL', '52', 'LOHAGARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (292, 4, 'KHULNA', '65', 'NARAIL', '76', 'NARAIL SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (293, 4, 'KHULNA', '87', 'SATKHIRA', '4', 'ASSASUNI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (294, 4, 'KHULNA', '87', 'SATKHIRA', '25', 'DEBHATA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (295, 4, 'KHULNA', '87', 'SATKHIRA', '43', 'KALAROA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (296, 4, 'KHULNA', '87', 'SATKHIRA', '47', 'KALIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (297, 4, 'KHULNA', '87', 'SATKHIRA', '82', 'SATKHIRA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (298, 4, 'KHULNA', '87', 'SATKHIRA', '86', 'SHYAMNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (299, 4, 'KHULNA', '87', 'SATKHIRA', '90', 'TALA')
GO
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (300, 4, 'KHULNA', '1', 'BAGERHAT', '8', 'BAGERHAT SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (301, 4, 'KHULNA', '1', 'BAGERHAT', '14', 'CHITALMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (302, 4, 'KHULNA', '1', 'BAGERHAT', '34', 'FAKIRHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (303, 4, 'KHULNA', '1', 'BAGERHAT', '38', 'KACHUA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (304, 4, 'KHULNA', '1', 'BAGERHAT', '56', 'MOLLAHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (305, 4, 'KHULNA', '1', 'BAGERHAT', '58', 'MONGLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (306, 4, 'KHULNA', '1', 'BAGERHAT', '60', 'MORRELGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (307, 4, 'KHULNA', '1', 'BAGERHAT', '73', 'RAMPAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (308, 4, 'KHULNA', '1', 'BAGERHAT', '77', 'SARANKHOLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (309, 4, 'KHULNA', '44', 'JHENAIDAH', '14', 'HARINAKUNDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (310, 4, 'KHULNA', '44', 'JHENAIDAH', '19', 'JHENAIDAH SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (311, 4, 'KHULNA', '44', 'JHENAIDAH', '33', 'KALIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (312, 4, 'KHULNA', '44', 'JHENAIDAH', '42', 'KOTCHANDPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (313, 4, 'KHULNA', '44', 'JHENAIDAH', '71', 'MAHESHPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (314, 4, 'KHULNA', '44', 'JHENAIDAH', '80', 'SHAILKUPA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (315, 4, 'KHULNA', '41', 'JESSORE', '4', 'ABHAYNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (316, 4, 'KHULNA', '41', 'JESSORE', '9', 'BAGHER PARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (317, 4, 'KHULNA', '41', 'JESSORE', '11', 'CHAUGACHHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (318, 4, 'KHULNA', '41', 'JESSORE', '23', 'JHIKARGACHHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (319, 4, 'KHULNA', '41', 'JESSORE', '38', 'KESHABPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (320, 4, 'KHULNA', '41', 'JESSORE', '47', 'JESSOR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (321, 4, 'KHULNA', '41', 'JESSORE', '61', 'MANIRAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (322, 4, 'KHULNA', '41', 'JESSORE', '90', 'SHARSHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (323, 4, 'KHULNA', '47', 'KHULNA', '12', 'BATIAGHATA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (324, 4, 'KHULNA', '47', 'KHULNA', '17', 'DACOPE')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (325, 4, 'KHULNA', '47', 'KHULNA', '21', 'DAULATPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (326, 4, 'KHULNA', '47', 'KHULNA', '30', 'DUMURIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (327, 4, 'KHULNA', '47', 'KHULNA', '40', 'DIGHALIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (328, 4, 'KHULNA', '47', 'KHULNA', '45', 'KHALISHPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (329, 4, 'KHULNA', '47', 'KHULNA', '48', 'KHAN JAHAN ALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (330, 4, 'KHULNA', '47', 'KHULNA', '51', 'KHULNA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (331, 4, 'KHULNA', '47', 'KHULNA', '53', 'KOYRA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (332, 4, 'KHULNA', '47', 'KHULNA', '64', 'PAIKGACHHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (333, 4, 'KHULNA', '47', 'KHULNA', '69', 'PHULTALA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (334, 4, 'KHULNA', '47', 'KHULNA', '75', 'RUPSA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (335, 4, 'KHULNA', '47', 'KHULNA', '85', 'SONADANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (336, 4, 'KHULNA', '47', 'KHULNA', '94', 'TEROKHADA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (337, 4, 'KHULNA', '57', 'MEHERPUR', '47', 'GANGNI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (338, 4, 'KHULNA', '57', 'MEHERPUR', '60', 'MUJIB NAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (339, 4, 'KHULNA', '57', 'MEHERPUR', '87', 'MEHERPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (340, 4, 'KHULNA', 7, 'MAGURA', '57', 'MAGURA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (341, 4, 'KHULNA', 7, 'MAGURA', '66', 'MOHAMMADPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (342, 4, 'KHULNA', 7, 'MAGURA', '85', 'SHALIKHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (343, 4, 'KHULNA', 7, 'MAGURA', '95', 'SREEPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (344, 4, 'KHULNA', '18', 'CHUADANGA', '7', 'ALAMDANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (345, 4, 'KHULNA', '18', 'CHUADANGA', '23', 'CHUADANGA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (346, 4, 'KHULNA', '18', 'CHUADANGA', '31', 'DAMURHUDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (347, 4, 'KHULNA', '18', 'CHUADANGA', '55', 'JIBAN NAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (348, 5, 'MYMENSINGH', '89', 'SHERPUR', '37', 'JHENAIGATI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (349, 5, 'MYMENSINGH', '89', 'SHERPUR', '67', 'NAKLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (350, 5, 'MYMENSINGH', '89', 'SHERPUR', '70', 'NALITABARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (351, 5, 'MYMENSINGH', '89', 'SHERPUR', '88', 'SHERPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (352, 5, 'MYMENSINGH', '89', 'SHERPUR', '90', 'SREEBARDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (353, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '13', 'BHALUKA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (354, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '16', 'DHOBAURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (355, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '20', 'FULBARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (356, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '22', 'GAFFARGAO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (357, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '23', 'GAURIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (358, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '24', 'HALUAGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (359, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '31', 'ISHWARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (360, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '52', 'MYMENSINGH SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (361, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '65', 'MUKTAGACHHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (362, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '72', 'NANDAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (363, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '81', 'PHULPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (364, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '88', 'TARAKANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (365, 5, 'MYMENSINGH', '61', 'MYMENSINGH', '94', 'TRISHAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (366, 5, 'MYMENSINGH', '72', 'NETRAKONA', '4', 'ATPARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (367, 5, 'MYMENSINGH', '72', 'NETRAKONA', '9', 'BARHATTA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (368, 5, 'MYMENSINGH', '72', 'NETRAKONA', '18', 'DURGAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (369, 5, 'MYMENSINGH', '72', 'NETRAKONA', '38', 'KHALIAJURI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (370, 5, 'MYMENSINGH', '72', 'NETRAKONA', '40', 'KALMAKANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (371, 5, 'MYMENSINGH', '72', 'NETRAKONA', '47', 'KENDUA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (372, 5, 'MYMENSINGH', '72', 'NETRAKONA', '56', 'MADA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (373, 5, 'MYMENSINGH', '72', 'NETRAKONA', '63', 'MOHANGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (374, 5, 'MYMENSINGH', '72', 'NETRAKONA', '74', 'NETROKONA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (375, 5, 'MYMENSINGH', '72', 'NETRAKONA', '83', 'PURBADHALA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (376, 5, 'MYMENSINGH', '39', 'JAMALPUR', '7', 'BAKSHIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (377, 5, 'MYMENSINGH', '39', 'JAMALPUR', '15', 'DEWANGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (378, 5, 'MYMENSINGH', '39', 'JAMALPUR', '29', 'ISLAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (379, 5, 'MYMENSINGH', '39', 'JAMALPUR', '36', 'JAMALPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (380, 5, 'MYMENSINGH', '39', 'JAMALPUR', '58', 'MADARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (381, 5, 'MYMENSINGH', '39', 'JAMALPUR', '61', 'MELANDAHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (382, 5, 'MYMENSINGH', '39', 'JAMALPUR', '85', 'SARISHABARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (383, 6, 'RAJSHAHI', '76', 'PABNA', '5', 'ATGHARIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (384, 6, 'RAJSHAHI', '76', 'PABNA', '16', 'BERA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (385, 6, 'RAJSHAHI', '76', 'PABNA', '19', 'BHANGURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (386, 6, 'RAJSHAHI', '76', 'PABNA', '22', 'CHATMOHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (387, 6, 'RAJSHAHI', '76', 'PABNA', '33', 'FARIDPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (388, 6, 'RAJSHAHI', '76', 'PABNA', '39', 'ISHWARDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (389, 6, 'RAJSHAHI', '76', 'PABNA', '55', 'PABNA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (390, 6, 'RAJSHAHI', '76', 'PABNA', '72', 'SANTHIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (391, 6, 'RAJSHAHI', '76', 'PABNA', '83', 'SUJANAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (392, 6, 'RAJSHAHI', '64', 'NAOGAO', '3', 'ATRAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (393, 6, 'RAJSHAHI', '64', 'NAOGAO', '6', 'BADALGACHHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (394, 6, 'RAJSHAHI', '64', 'NAOGAO', '28', 'DHAMOIRHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (395, 6, 'RAJSHAHI', '64', 'NAOGAO', '47', 'MANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (396, 6, 'RAJSHAHI', '64', 'NAOGAO', '50', 'MAHADEBPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (397, 6, 'RAJSHAHI', '64', 'NAOGAO', '60', 'NAOGAON SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (398, 6, 'RAJSHAHI', '64', 'NAOGAO', '69', 'NIAMATPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (399, 6, 'RAJSHAHI', '64', 'NAOGAO', '75', 'PATNITALA')
GO
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (400, 6, 'RAJSHAHI', '64', 'NAOGAO', '79', 'PORSHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (401, 6, 'RAJSHAHI', '64', 'NAOGAO', '85', 'RANINAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (402, 6, 'RAJSHAHI', '64', 'NAOGAO', '86', 'SAPAHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (403, 6, 'RAJSHAHI', '69', 'NATORE', '9', 'BAGATIPARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (404, 6, 'RAJSHAHI', '69', 'NATORE', '15', 'BARAIGRAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (405, 6, 'RAJSHAHI', '69', 'NATORE', '41', 'GURUDASPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (406, 6, 'RAJSHAHI', '69', 'NATORE', '44', 'LALPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (407, 6, 'RAJSHAHI', '69', 'NATORE', '55', 'NALDANGA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (408, 6, 'RAJSHAHI', '69', 'NATORE', '63', 'NATORE SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (409, 6, 'RAJSHAHI', '69', 'NATORE', '91', 'SINGRA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (410, 6, 'RAJSHAHI', '70', 'CHAPAINAWABGANJ ', '18', 'BHOLAHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (411, 6, 'RAJSHAHI', '70', 'CHAPAINAWABGANJ ', '37', 'GOMASTAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (412, 6, 'RAJSHAHI', '70', 'CHAPAINAWABGANJ ', '56', 'NACHOLE')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (413, 6, 'RAJSHAHI', '70', 'CHAPAINAWABGANJ ', '66', 'CHAPAI NABABGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (414, 6, 'RAJSHAHI', '70', 'CHAPAINAWABGANJ ', '88', 'SHIBGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (415, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '11', 'BELKUCHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (416, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '27', 'CHAUHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (417, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '44', 'KAMARKHANDA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (418, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '50', 'KAZIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (419, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '61', 'ROYGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (420, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '67', 'SHAHJADPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (421, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '78', 'SIRAJGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (422, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '89', 'TARASH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (423, 6, 'RAJSHAHI', '88', 'SIRAJGANJ', '94', 'ULLAH PARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (424, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '10', 'BAGHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (425, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '12', 'BAGHMARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (426, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '22', 'BOALIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (427, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '25', 'CHARGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (428, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '31', 'DURGAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (429, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '34', 'GODAGARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (430, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '40', 'MATIHAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (431, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '53', 'MOHANPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (432, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '72', 'PABA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (433, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '82', 'PUTHIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (434, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '85', 'RAJPARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (435, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '90', 'SHAH MAKHDUM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (436, 6, 'RAJSHAHI', '81', 'RAJSHAHI', '94', 'TANORE')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (437, 6, 'RAJSHAHI', '10', 'BOGRA', '6', 'ADAMDIGHI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (438, 6, 'RAJSHAHI', '10', 'BOGRA', '20', 'BOGRA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (439, 6, 'RAJSHAHI', '10', 'BOGRA', '27', 'DHUNAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (440, 6, 'RAJSHAHI', '10', 'BOGRA', '33', 'DHUPCHANCHIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (441, 6, 'RAJSHAHI', '10', 'BOGRA', '40', 'GABTALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (442, 6, 'RAJSHAHI', '10', 'BOGRA', '54', 'KAHALOO')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (443, 6, 'RAJSHAHI', '10', 'BOGRA', '67', 'NANDIGRAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (444, 6, 'RAJSHAHI', '10', 'BOGRA', '81', 'SARIAKANDI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (445, 6, 'RAJSHAHI', '10', 'BOGRA', '85', 'SHAJAHANPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (446, 6, 'RAJSHAHI', '10', 'BOGRA', '88', 'SHERPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (447, 6, 'RAJSHAHI', '10', 'BOGRA', '94', 'SHIBGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (448, 6, 'RAJSHAHI', '10', 'BOGRA', '95', 'SONATOLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (449, 6, 'RAJSHAHI', '49', 'KURIGRAM', '6', 'BHURUNGAMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (450, 6, 'RAJSHAHI', '49', 'KURIGRAM', '8', 'CHAR RAJIBPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (451, 6, 'RAJSHAHI', '49', 'KURIGRAM', '9', 'CHILMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (452, 6, 'RAJSHAHI', '49', 'KURIGRAM', '18', 'PHULBARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (453, 6, 'RAJSHAHI', '49', 'KURIGRAM', '52', 'KURIGRAM SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (454, 6, 'RAJSHAHI', '49', 'KURIGRAM', '61', 'NAGESHWARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (455, 6, 'RAJSHAHI', '49', 'KURIGRAM', '77', 'RAJARHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (456, 6, 'RAJSHAHI', '49', 'KURIGRAM', '79', 'RAUMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (457, 6, 'RAJSHAHI', '49', 'KURIGRAM', '94', 'ULIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (458, 6, 'RAJSHAHI', '38', 'JOYPURHAT', '13', 'AKKELPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (459, 6, 'RAJSHAHI', '38', 'JOYPURHAT', '47', 'JOYPURHAT SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (460, 6, 'RAJSHAHI', '38', 'JOYPURHAT', '58', 'KALAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (461, 6, 'RAJSHAHI', '38', 'JOYPURHAT', '61', 'KHETLAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (462, 6, 'RAJSHAHI', '38', 'JOYPURHAT', '74', 'PANCHBIBI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (463, 7, 'RANPUR', '32', 'GAIBANDHA', '21', 'FULCHHARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (464, 7, 'RANPUR', '32', 'GAIBANDHA', '24', 'GAIBANDHA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (465, 7, 'RANPUR', '32', 'GAIBANDHA', '30', 'GOBINDAGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (466, 7, 'RANPUR', '32', 'GAIBANDHA', '67', 'PALASHBARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (467, 7, 'RANPUR', '32', 'GAIBANDHA', '82', 'SADULLAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (468, 7, 'RANPUR', '32', 'GAIBANDHA', '88', 'SAGHATA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (469, 7, 'RANPUR', '32', 'GAIBANDHA', '91', 'SUNDARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (470, 7, 'RANPUR', '50', 'KUSHTIA', '15', 'BHERAMARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (471, 7, 'RANPUR', '50', 'KUSHTIA', '39', 'DAULATPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (472, 7, 'RANPUR', '50', 'KUSHTIA', '63', 'KHOKSA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (473, 7, 'RANPUR', '50', 'KUSHTIA', '71', 'KUMARKHALI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (474, 7, 'RANPUR', '50', 'KUSHTIA', '79', 'KUSHTIA SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (475, 7, 'RANPUR', '50', 'KUSHTIA', '94', 'MIRPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (476, 7, 'RANPUR', '52', 'LALMONIRHAT', '2', 'ADITMARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (477, 7, 'RANPUR', '52', 'LALMONIRHAT', '33', 'HATIBANDHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (478, 7, 'RANPUR', '52', 'LALMONIRHAT', '39', 'KALIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (479, 7, 'RANPUR', '52', 'LALMONIRHAT', '55', 'LALMONIRHAT SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (480, 7, 'RANPUR', '52', 'LALMONIRHAT', '70', 'PATGRAM')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (481, 7, 'RANPUR', '27', 'DINAJPUR', '10', 'BIRAMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (482, 7, 'RANPUR', '27', 'DINAJPUR', '12', 'BIRGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (483, 7, 'RANPUR', '27', 'DINAJPUR', '17', 'BIRAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (484, 7, 'RANPUR', '27', 'DINAJPUR', '21', 'BOCHAGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (485, 7, 'RANPUR', '27', 'DINAJPUR', '30', 'CHIRIRBANDAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (486, 7, 'RANPUR', '27', 'DINAJPUR', '38', 'FULBARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (487, 7, 'RANPUR', '27', 'DINAJPUR', '43', 'GHORAGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (488, 7, 'RANPUR', '27', 'DINAJPUR', '47', 'HAKIMPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (489, 7, 'RANPUR', '27', 'DINAJPUR', '56', 'KAHAROLE')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (490, 7, 'RANPUR', '27', 'DINAJPUR', '60', 'KHANSAMA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (491, 7, 'RANPUR', '27', 'DINAJPUR', '64', 'DINAJPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (492, 7, 'RANPUR', '27', 'DINAJPUR', '69', 'NAWABGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (493, 7, 'RANPUR', '27', 'DINAJPUR', '77', 'PARBATIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (494, 7, 'RANPUR', '85', 'RANGPUR', '3', 'BADARGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (495, 7, 'RANPUR', '85', 'RANGPUR', '27', 'GANGACHARA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (496, 7, 'RANPUR', '85', 'RANGPUR', '42', 'KAUNIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (497, 7, 'RANPUR', '85', 'RANGPUR', '49', 'RANGPUR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (498, 7, 'RANPUR', '85', 'RANGPUR', '58', 'MITHA PUKUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (499, 7, 'RANPUR', '85', 'RANGPUR', '73', 'PIRGACHHA')
GO
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (500, 7, 'RANPUR', '85', 'RANGPUR', '76', 'PIRGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (501, 7, 'RANPUR', '85', 'RANGPUR', '92', 'TARAGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (502, 7, 'RANPUR', '77', 'PANCHAGARH', '4', 'ATWARI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (503, 7, 'RANPUR', '77', 'PANCHAGARH', '25', 'BODA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (504, 7, 'RANPUR', '77', 'PANCHAGARH', '34', 'DEBIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (505, 7, 'RANPUR', '77', 'PANCHAGARH', '73', 'PANCHAGARH SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (506, 7, 'RANPUR', '77', 'PANCHAGARH', '90', 'TENTULIA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (507, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '12', 'DIMLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (508, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '15', 'DOMAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (509, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '36', 'JALDHAKA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (510, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '45', 'KISHOREGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (511, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '64', 'NILPHAMARI SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (512, 7, 'RANPUR', '73', 'NILPHAMARI ZILA', '85', 'SAIDPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (513, 7, 'RANPUR', '94', 'THAKURGAO', '8', 'BALIADANGI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (514, 7, 'RANPUR', '94', 'THAKURGAO', '51', 'HARIPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (515, 7, 'RANPUR', '94', 'THAKURGAO', '82', 'PIRGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (516, 7, 'RANPUR', '94', 'THAKURGAO', '86', 'RANISANKAIL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (517, 7, 'RANPUR', '94', 'THAKURGAO', '94', 'THAKURGAON SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (518, 8, 'SYLHET', '90', 'SUNAMGANJ', '18', 'BISHWAMBARPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (519, 8, 'SYLHET', '90', 'SUNAMGANJ', '23', 'CHHATAK')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (520, 8, 'SYLHET', '90', 'SUNAMGANJ', '27', 'DAKSHIN SUNAMGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (521, 8, 'SYLHET', '90', 'SUNAMGANJ', '29', 'DERAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (522, 8, 'SYLHET', '90', 'SUNAMGANJ', '32', 'DHARAMPASHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (523, 8, 'SYLHET', '90', 'SUNAMGANJ', '33', 'DOWARABAZAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (524, 8, 'SYLHET', '90', 'SUNAMGANJ', '47', 'JAGANNATHPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (525, 8, 'SYLHET', '90', 'SUNAMGANJ', '50', 'JAMALGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (526, 8, 'SYLHET', '90', 'SUNAMGANJ', '86', 'SULLA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (527, 8, 'SYLHET', '90', 'SUNAMGANJ', '89', 'SUNAMGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (528, 8, 'SYLHET', '90', 'SUNAMGANJ', '92', 'TAHIRPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (529, 8, 'SYLHET', '91', 'SYLHET', '8', 'BALAGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (530, 8, 'SYLHET', '91', 'SYLHET', '17', 'BEANI BAZAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (531, 8, 'SYLHET', '91', 'SYLHET', '20', 'BISHWANATH')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (532, 8, 'SYLHET', '91', 'SYLHET', '27', 'COMPANIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (533, 8, 'SYLHET', '91', 'SYLHET', '31', 'DAKSHIN SURMA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (534, 8, 'SYLHET', '91', 'SYLHET', '35', 'FENCHUGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (535, 8, 'SYLHET', '91', 'SYLHET', '38', 'GOLAPGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (536, 8, 'SYLHET', '91', 'SYLHET', '41', 'GOWAINGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (537, 8, 'SYLHET', '91', 'SYLHET', '53', 'JAINTIAPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (538, 8, 'SYLHET', '91', 'SYLHET', '59', 'KANAIGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (539, 8, 'SYLHET', '91', 'SYLHET', '60', 'Osmaninagar')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (540, 8, 'SYLHET', '91', 'SYLHET', '62', 'SYLHET SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (541, 8, 'SYLHET', '91', 'SYLHET', '94', 'ZAKIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (542, 8, 'SYLHET', '58', 'MAULVIBAZAR', '14', 'BARLEKHA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (543, 8, 'SYLHET', '58', 'MAULVIBAZAR', '35', 'JURI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (544, 8, 'SYLHET', '58', 'MAULVIBAZAR', '56', 'KAMALGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (545, 8, 'SYLHET', '58', 'MAULVIBAZAR', '65', 'KULAURA')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (546, 8, 'SYLHET', '58', 'MAULVIBAZAR', '74', 'MAULVIBAZAR SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (547, 8, 'SYLHET', '58', 'MAULVIBAZAR', '80', 'RAJNAGAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (548, 8, 'SYLHET', '58', 'MAULVIBAZAR', '83', 'SREEMANGAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (549, 8, 'SYLHET', '36', 'HABIGANJ', '2', 'AJMIRIGANJ')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (550, 8, 'SYLHET', '36', 'HABIGANJ', '5', 'BAHUBAL')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (551, 8, 'SYLHET', '36', 'HABIGANJ', '11', 'BANIACHONG')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (552, 8, 'SYLHET', '36', 'HABIGANJ', '26', 'CHUNARUGHAT')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (553, 8, 'SYLHET', '36', 'HABIGANJ', '44', 'HABIGANJ SADAR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (554, 8, 'SYLHET', '36', 'HABIGANJ', '68', 'LAKHAI')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (555, 8, 'SYLHET', '36', 'HABIGANJ', '71', 'MADHABPUR')
INSERT into thana (id, division_id, division_name, district_id, district_name, thana_id, name) VALUES (556, 8, 'SYLHET', '36', 'HABIGANJ', '77', 'NABIGANJ')