--liquibase formatted sql

--changeset author:alvi
INSERT into district (division_id,district_id,name) VALUES ('4','1','BAGERHAT')
INSERT into district (division_id,district_id,name) VALUES ('2', '3', 'BANDARBAN')
INSERT into district (division_id,district_id,name) VALUES ('1', '4', 'BARGUNA')
INSERT into district  (division_id,district_id,name) VALUES ('1', '6', 'BARISAL')
INSERT into district  (division_id,district_id,name) VALUES ('1', '9', 'BHOLA')
INSERT into district  (division_id,district_id,name) VALUES ('6', '10', 'BOGRA')
INSERT into district  (division_id,district_id,name) VALUES ('2', '12', 'BRAHMANBARIA')
INSERT into district  (division_id,district_id,name) VALUES ('2', '13', 'CHANDPUR')
INSERT into district  (division_id,district_id,name) VALUES ('2', '15', 'CHITTAGONG')
INSERT into district  (division_id,district_id,name) VALUES ('4', '18', 'CHUADANGA')
INSERT into district  (division_id,district_id,name) VALUES ('2', '19', 'COMILLA')
INSERT into district  (division_id,district_id,name) VALUES ('2', '22', 'Coxbazar')
INSERT into district  (division_id,district_id,name) VALUES ('3', '26', 'DHAKA')
INSERT into district  (division_id,district_id,name) VALUES ('7', '27', 'DINAJPUR')
INSERT into district  (division_id,district_id,name) VALUES ('3', '29', 'FARIDPUR')
INSERT into district  (division_id,district_id,name) VALUES ('2', '30', 'FENI')
INSERT into district  (division_id,district_id,name) VALUES ('7', '32', 'GAIBANDHA')
INSERT into district  (division_id,district_id,name) VALUES ('3', '33', 'GAZIPUR')
INSERT into district  (division_id,district_id,name) VALUES ('3', '35', 'GOPALGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('8', '36', 'HABIGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('6', '38', 'JOYPURHAT')
INSERT into district  (division_id,district_id,name) VALUES ('5', '39', 'JAMALPUR')
INSERT into district  (division_id,district_id,name) VALUES ('4', '41', 'JESSORE')
INSERT into district  (division_id,district_id,name) VALUES ('1', '42', 'JHALOKATI')
INSERT into district  (division_id,district_id,name) VALUES ('4', '44', 'JHENAIDAH')
INSERT into district  (division_id,district_id,name) VALUES ('2', '46', 'KHAGRACHHARI')
INSERT into district  (division_id,district_id,name) VALUES ('4', '47', 'KHULNA')
INSERT into district  (division_id,district_id,name) VALUES ('3','48', 'KISHOREGONJ')
INSERT into district  (division_id,district_id,name) VALUES ('6','49', 'KURIGRAM')
INSERT into district  (division_id,district_id,name) VALUES ('7','50', 'KUSHTIA')
INSERT into district  (division_id,district_id,name) VALUES ('2','51', 'LAKSHMIPUR')
INSERT into district  (division_id,district_id,name) VALUES ('7','52', 'LALMONIRHAT')
INSERT into district  (division_id,district_id,name) VALUES ('3','54', 'MADARIPUR')
INSERT into district  (division_id,district_id,name) VALUES ('4','55', 'MAGURA')
INSERT into district  (division_id,district_id,name) VALUES ('3','56', 'MANIKGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('4','57', 'MEHERPUR')
INSERT into district  (division_id,district_id,name) VALUES ('8','58', 'MAULVIBAZAR')
INSERT into district  (division_id,district_id,name) VALUES ('3','59', 'MUNSHIGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('5','61', 'MYMENSINGH')
INSERT into district  (division_id,district_id,name) VALUES ('6','64', 'NAOGAON')
INSERT into district  (division_id,district_id,name) VALUES ('4','65', 'NARAIL')
INSERT into district  (division_id,district_id,name) VALUES ('3','67', 'NARAYANGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('3','68', 'NARSINGDI')
INSERT into district  (division_id,district_id,name) VALUES ('6','69', 'NATORE')
INSERT into district  (division_id,district_id,name) VALUES ('6','70', 'CHAPAINAWABGANJ ')
INSERT into district  (division_id,district_id,name) VALUES ('5','72','NETRAKONA')
INSERT into district  (division_id,district_id,name) VALUES ('7','73','NILPHAMARI ZILA')
INSERT into district  (division_id,district_id,name) VALUES ('2','75','NOAKHALI')
INSERT into district  (division_id,district_id,name) VALUES ('6','76','PABNA')
INSERT into district  (division_id,district_id,name) VALUES ('7','77','PANCHAGARH')
INSERT into district  (division_id,district_id,name) VALUES ('1','78','PATUAKHALI')
INSERT into district  (division_id,district_id,name) VALUES ('1','79','PIROJPUR')
INSERT into district  (division_id,district_id,name) VALUES ('6','81','RAJSHAHI')
INSERT into district  (division_id,district_id,name) VALUES ('3','82','RAJBARI')
INSERT into district  (division_id,district_id,name) VALUES ('2','84','RANGAMATI')
INSERT into district  (division_id,district_id,name) VALUES ('7','85','RANGPUR')
INSERT into district  (division_id,district_id,name) VALUES ('3','86','SHARIATPUR')
INSERT into district  (division_id,district_id,name) VALUES ('4','87','SATKHIRA')
INSERT into district  (division_id,district_id,name) VALUES ('6','88','SIRAJGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('5','89','SHERPUR')
INSERT into district  (division_id,district_id,name) VALUES ('8','90','SUNAMGANJ')
INSERT into district  (division_id,district_id,name) VALUES ('8','91','SYLHET')
INSERT into district  (division_id,district_id,name) VALUES ('3','93','TANGAIL')
INSERT into district  (division_id,district_id,name) VALUES ('7','94','THAKURGAON')
